package com.penthera.download2goandroidx

import android.annotation.SuppressLint
import android.os.Bundle
import android.view.View
import android.widget.Button
import android.widget.ProgressBar
import android.widget.TextView
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.LiveData
import androidx.lifecycle.Observer
import com.penthera.virtuososdk.Common
import com.penthera.virtuososdk.androidxsupport.SegmentedAssetLiveData
import com.penthera.virtuososdk.androidxsupport.VirtuosoLiveDataFactory
import com.penthera.virtuososdk.client.*
import com.penthera.virtuososdk.client.builders.HLSAssetBuilder
import java.net.URL

class MainActivity : AppCompatActivity() {

    private lateinit var virtuosoLiveDataFactory: VirtuosoLiveDataFactory
    private lateinit var  virtuoso : Virtuoso
    var asset : IAsset? =  null
    var segmentedAssetLiveData : SegmentedAssetLiveData? = null

    private lateinit var dlBtn : Button
    private lateinit var plBtn : Button
    private lateinit var delBtn : Button

    private lateinit var textView: TextView
    private lateinit var statusView: TextView;
    private lateinit var progressBar: ProgressBar

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        dlBtn = findViewById(R.id.download)
        dlBtn.setOnClickListener { downloadAsset() }
        plBtn= findViewById(R.id.play)
        plBtn.setOnClickListener { playAsset()}
        delBtn = findViewById(R.id.delete)
        delBtn.setOnClickListener { deleteAsset() }

        textView = findViewById(R.id.textView)
        statusView = findViewById(R.id.engineStatusView)
        progressBar = findViewById(R.id.progressBar)

        initVirtuosoSDK(savedInstanceState)

        updateUI()
    }

    private fun initVirtuosoSDK(savedInstanceState: Bundle?) {

        virtuosoLiveDataFactory = VirtuosoLiveDataFactory.getInstance()
        virtuoso = virtuosoLiveDataFactory.createVirtuosoWithLifecycle(this, this)

        val engineStatus: LiveData<Int> = virtuosoLiveDataFactory.engineStatus
        engineStatus.observe(this,
            Observer { statusVal: Int? ->
                statusView.setText(
                    getString(
                        R.string.engine_status, getStatusString(
                            statusVal!!
                        )
                    )
                )
            })


        //this is the current best practice for initializing the SDK
        if(savedInstanceState == null){//initial start of activity will have null saved instance state
            val status = virtuoso.backplane?.authenticationStatus
            if(status == Common.AuthenticationStatus.NOT_AUTHENTICATED){//if not authenticated execute sdk startup
                //here we use the simplest login with hard coded values

                virtuoso.startup(
                    URL(BACKPLANE_URL),//substitute the proper backplane url for you implementation
                    virtuoso.backplane?.settings?.deviceId,//provide an appropriate unique user id.  Virtuoso SDK device id used here for convenience
                    null, //Optional additional device id to be associated with the user account.  This is not the device id generated by the virtuoso SDK
                    BACKPLANE_PUBLIC_KEY,//Penthera demo public key.  Substitute the correct one.
                    BACKPLANE_PRIVATE_KEY
                ) { _, _ ->}//callback lambda for push registration.  this will be detailed in subsequent tutorials

            }

        }

        // Load asset if it has already been downloaded
        loadAsset()
    }

    private fun loadAsset() {
        segmentedAssetLiveData?.removeObservers(this)
        segmentedAssetLiveData = virtuosoLiveDataFactory.getAssetStatus(ASSET_ID)
        segmentedAssetLiveData?.observe(this, Observer { updatedAssetVal: ISegmentedAsset? ->
            asset = updatedAssetVal
            updateAssetUI()
        })
    }

    fun updateUI() {
        dlBtn.isEnabled = asset == null
        plBtn.isEnabled = asset != null
        delBtn.isEnabled = asset != null
        if (asset == null) {
            textView.text = ""
        }
    }

    private fun playAsset() {

        if(asset != null) {
            VideoPlayerActivity.playVideoDownload(asset!!, this)
        }

    }

    private fun deleteAsset() {
        virtuoso.assetManager.delete(asset)
        asset = null
        updateUI()
    }


    private fun downloadAsset(){

        val params = HLSAssetBuilder().apply {
            assetId(ASSET_ID) //REQUIRED PARAMETER asset ID of the new asset
            manifestUrl(URL(ASSET_URL)) //REQUIRED PARAMETER  url of the new asset
            assetObserver(AssetParseObserver(this@MainActivity))//REQUIRED PARAMETER observer that will be notified of parsing status
            addToQueue(true) // add to the download queue after parsing complete
            desiredVideoBitrate(Integer.MAX_VALUE)//specify a bitrate for desired video quality Integer.MAX_VALUE for largest available
            withMetadata(ASSET_TITLE)//user specified descriptive text for the asset.  Here we supply a title.
        }.build()

        virtuoso.assetManager.createHLSSegmentedAssetAsync(params)

        loadAsset()
    }

    private fun updateAssetUI() {

        var progress: Int = -1
        var assetStatus = ""
        var value = ""
        var errorCount: Long = 0

        asset?.let {

            progress = (it.fractionComplete * 100.0).toInt()

            when (it.downloadStatus) {

                Common.AssetStatus.DOWNLOADING -> {
                    assetStatus = getString(R.string.status_downloading)
                    value = getString(R.string.asset_status_downloading)
                }

                Common.AssetStatus.DOWNLOAD_COMPLETE -> {
                    assetStatus = getString(R.string.status_downloaded)
                    value = getString(R.string.asset_status_complete)
                }

                Common.AssetStatus.EXPIRED -> {
                    assetStatus = getString(R.string.status_expired)
                    value = getString(R.string.asset_status_expired)
                }

                Common.AssetStatus.DOWNLOAD_DENIED_ASSET -> {
                    assetStatus = getString(R.string.status_queued)
                    value = getString(R.string.asset_status_denied_mad)
                }

                Common.AssetStatus.DOWNLOAD_DENIED_ACCOUNT -> {
                    assetStatus = getString(R.string.status_queued)
                    value = getString(R.string.asset_status_denied_mda)
                }

                Common.AssetStatus.DOWNLOAD_DENIED_EXTERNAL_POLICY -> {
                    assetStatus = getString(R.string.status_queued)
                    value = getString(R.string.asset_status_denied_ext)
                }

                Common.AssetStatus.DOWNLOAD_DENIED_MAX_DEVICE_DOWNLOADS -> {
                    assetStatus = getString(R.string.status_queued)
                    value = getString(R.string.asset_status_denied_mpd)
                }

                Common.AssetStatus.DOWNLOAD_BLOCKED_AWAITING_PERMISSION -> {
                    assetStatus = getString(R.string.status_queued)
                    value = getString(R.string.asset_status_await_permission)
                }

                Common.AssetStatus.DOWNLOAD_DENIED_COPIES -> {
                    assetStatus = getString(R.string.status_queued)
                    value = getString(R.string.asset_status_denied_copies)
                }

                else -> {
                    assetStatus = getString(R.string.status_pending)
                    value = getString(R.string.asset_status_pending)
                }
            }

            errorCount = it.errorCount
        }

        updateUI()

        textView.visibility = View.VISIBLE
        textView.text = getString(R.string.asset_status, assetStatus, errorCount, value)

        // Tiny Progress
        if (progress == 0) progress = 1

        // Progress Bar
        if (progress in 1..99) {
            progressBar.progress = progress
            progressBar.visibility = View.VISIBLE
        } else {
            progressBar.visibility = View.GONE
        }
    }

    class AssetParseObserver(activity: AppCompatActivity) : ISegmentedAssetFromParserObserver{

        private var mActivty : AppCompatActivity = activity

        @SuppressLint("ShowToast")
        override fun complete(asset: ISegmentedAsset?, error: Int, addedToQueue: Boolean) {

            if(asset != null){
               Toast.makeText(
                   mActivty,
                   "Asset parsed and " + if (addedToQueue) "added" else "not added" + "to download queue",
                   Toast.LENGTH_LONG
               ).show()

            }
            else{
                Toast.makeText(mActivty, "Error $error while parsing asset", Toast.LENGTH_LONG).show()
            }
        }
    }

    private fun getStatusString(engineStatus: Int): String? {
        val status: String
        status = when (engineStatus) {
            Common.EngineStatus.DOWNLOADING -> "Downloading"
            Common.EngineStatus.PAUSED -> "Paused"
            Common.EngineStatus.DISABLED -> "Download Disabled"
            Common.EngineStatus.BLOCKED -> "Blocked"
            Common.EngineStatus.ERROR -> "Errored"
            Common.EngineStatus.AUTH_FAILURE -> "Auth Failure"
            Common.EngineStatus.IDLE -> "Idle"
            else -> "Idle"
        }
        return status
    }

    companion object{
        // Important: Asset ID should be unique across your video catalog
        const val ASSET_ID : String = "TEST_ASSET_ID"
        const val ASSET_TITLE : String = "TEST ASSET"
        const val ASSET_URL: String = "http://virtuoso-demo-content.s3.amazonaws.com/Steve/steve.m3u8"

        const val BACKPLANE_URL = "https://demo.penthera.com"
        const val BACKPLANE_PUBLIC_KEY =  "a382d4a927dee20c21af4442a85adfc8366b99b485547d7364818839509ac7cb"
        const val BACKPLANE_PRIVATE_KEY = "517ba3db3fb8127d33b342716b69bdbdb030425737a3ade7d2224b86fdf8bf19"

    }
}
